"""Pinocchio engine fingerprint (schema ``model-fingerprint/v1``).

Builds an exercise URDF, loads it in the REAL Pinocchio engine with a
free-flyer root and reports what the engine sees, for comparison against the
canonical parity standard (see ``_canonical/conformance.py``).

Engine notes:

* Gravity is not part of URDF. Pinocchio's default ``model.gravity`` is
  ``(0, 0, -9.81)``; :func:`load_model` sets it from the standard
  (9.80665 m/s^2) explicitly, as the repo convention requires.
* Pinocchio has no contact model, so ``ground_friction`` is omitted.
* Barbell and fixture bodies are fixed-joint children that Pinocchio merges
  into their parent joint's inertia; human segment masses are therefore read
  from a second engine model built from the URDF with every fixed-joint
  subtree removed.
"""

from __future__ import annotations

import logging
import xml.etree.ElementTree as ET
from typing import Any

from pinocchio_models.model_pack import list_exercises, manifest
from pinocchio_models.shared.parity._canonical import assemble, conformance

logger = logging.getLogger(__name__)

ENGINE = "pinocchio"

# Pinocchio joint name -> canonical coordinate name (only names that differ).
COORDINATE_ALIASES: dict[str, str] = {
    **{f"elbow_{s}": f"elbow_{s}_flex" for s in ("l", "r")},
    **{f"knee_{s}": f"knee_{s}_flex" for s in ("l", "r")},
    "neck": "neck_flex",
}

# Pinocchio body (link) name -> canonical segment name; names already match.
SEGMENT_ALIASES: dict[str, str] = {}

# Registry ids of the optimisation objectives that differ from manifest ids.
_OBJECTIVE_IDS: dict[str, str] = {"squat": "back_squat"}


def _link_of(joint: ET.Element, tag: str) -> str:
    """Return the ``link`` attribute of a joint's ``<parent>``/``<child>``."""
    node = joint.find(tag)
    return "" if node is None else node.get("link", "")


def _fixed_subtree_links(joints: list[ET.Element]) -> set[str]:
    """Return every link at or below a fixed joint's child."""
    doomed: set[str] = set()
    frontier = [_link_of(j, "child") for j in joints if j.get("type") == "fixed"]
    while frontier:
        link = frontier.pop()
        doomed.add(link)
        frontier += [
            _link_of(j, "child") for j in joints if _link_of(j, "parent") == link
        ]
    return doomed


def _strip_fixed_subtrees(urdf: str) -> str:
    """Return *urdf* without fixed joints and the links hanging below them."""
    root = ET.fromstring(urdf)  # nosec B314 -- urdf is self-generated by build_urdf
    joints = root.findall("joint")
    doomed = _fixed_subtree_links(joints)
    for j in joints:
        if j.get("type") == "fixed" or _link_of(j, "child") in doomed:
            root.remove(j)
    for link_el in root.findall("link"):
        if link_el.get("name") in doomed:
            root.remove(link_el)
    return ET.tostring(root, encoding="unicode")


def build_urdf(exercise: str) -> str:
    """Return the URDF string for a manifest exercise id."""
    from pinocchio_models.__main__ import _BUILDERS, _MANIFEST_ID_ALIASES

    if exercise not in list_exercises():
        raise ValueError(f"unknown exercise {exercise!r}")
    return _BUILDERS[_MANIFEST_ID_ALIASES.get(exercise, exercise)]()


def load_model(urdf: str, std: dict[str, Any] | None = None) -> Any:
    """Load *urdf* in Pinocchio with a free-flyer root and standard gravity."""
    import numpy as np
    import pinocchio as pin

    std = std or conformance.load_standard()
    model = pin.buildModelFromXML(urdf, pin.JointModelFreeFlyer())
    model.gravity.linear = np.array([0.0, 0.0, -std["frame"]["gravity_mps2"]])
    return model


def _measure(
    urdf: str, std: dict[str, Any]
) -> tuple[dict[str, float], dict[str, list[float]]]:
    """Raw per-body masses and neutral world origins (engine frame).

    Read from a model with fixed-joint subtrees removed, because Pinocchio
    merges those bodies into their parent joint's inertia.
    """
    import pinocchio as pin

    model = load_model(_strip_fixed_subtrees(urdf), std)
    data = model.createData()
    pin.forwardKinematics(model, data, pin.neutral(model))
    pin.updateFramePlacements(model, data)
    masses: dict[str, float] = {}
    origins: dict[str, list[float]] = {}
    for fid, frame in enumerate(model.frames):
        if frame.type == pin.FrameType.BODY:
            masses[frame.name] = float(model.inertias[frame.parentJoint].mass)
            origins[frame.name] = [float(v) for v in data.oMf[fid].translation]
    return masses, origins


def _limits(model: Any) -> dict[str, tuple[float, float]]:
    """Raw 1-DOF joint limits keyed by engine joint name."""
    out: dict[str, tuple[float, float]] = {}
    for jid in range(2, model.njoints):  # 0 = universe, 1 = free-flyer root
        joint = model.joints[jid]
        if joint.nq == 1:
            q = joint.idx_q
            out[model.names[jid]] = (
                float(model.lowerPositionLimit[q]),
                float(model.upperPositionLimit[q]),
            )
    return out


def _phase_count(exercise: str) -> int | None:
    from pinocchio_models.optimization.objectives.registry import EXERCISE_OBJECTIVES

    objective = EXERCISE_OBJECTIVES.get(_OBJECTIVE_IDS.get(exercise, exercise))
    return None if objective is None else len(objective.phases)


def fingerprint(exercise: str) -> dict[str, Any]:
    """Build *exercise*, load it in Pinocchio and return its fingerprint."""
    std = conformance.load_standard()
    version = ""
    try:
        import pinocchio as pin

        version = str(pin.__version__)
        urdf = build_urdf(exercise)
        model = load_model(urdf, std)
        masses, origins = _measure(urdf, std)
    except Exception as exc:  # noqa: BLE001 - any load failure is reported
        logger.warning("%s failed to load in %s: %s", exercise, ENGINE, exc)
        return assemble.failed_fingerprint(ENGINE, version, exercise, exc)
    return assemble.assemble_fingerprint(
        engine=ENGINE,
        engine_version=version,
        exercise=exercise,
        std=std,
        root_joint="free" if model.joints[1].nq == 7 else "fixed",
        gravity_engine=[float(v) for v in model.gravity.linear],
        segment_masses_kg=masses,
        coordinate_limits_rad=_limits(model),
        segment_origins_engine_m=origins,
        capabilities=assemble.capabilities_from_manifest(manifest(), std),
        coordinate_aliases=COORDINATE_ALIASES,
        segment_aliases=SEGMENT_ALIASES,
        phase_count=_phase_count(exercise),
    )


def main(argv: list[str] | None = None) -> int:
    """CLI: write fingerprint JSON for one exercise or all of them."""
    return assemble.run_fingerprint_cli(argv, fingerprint, list_exercises(), ENGINE)


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
